config/routes.rb
Plexhack::Application.routes.draw do
  resources :video_notes

  resources :users

  resources :videos

  resources :servers

  resources :torrents

  match 'servers/:id/refresh' => 'servers#refresh'
  match 'servers/:id/videos' => 'servers#videos'
  match 'servers/:id/section/:section_id' => 'servers#section'
  match 'servers/:id/section/:section_id/refresh' => 'servers#section_refresh'

  root :to => 'servers#index'

end

app/models/server.rb
class Server < ActiveRecord::Base
  attr_accessible :address, :host, :name, :port
  has_many :videos
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    @server = Server.find(params[:id])

    @media = ServerMedia.new(@server)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end

  # GET /servers/1/refresh
  def refresh
    @server = Server.find(params[:id])

    @media = ServerMedia.new(@server)

    @videos = @media.refresh_media
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render json: @server, status: :created, location: @server }
      else
        format.html { render action: "new" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :no_content }
    end
  end

  # GET /videos
  # GET /videos.json
  def videos
    @videos = Video.find_all_by_server_id(params[:id])
    print @videos.size

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos
  # GET /videos.json
  def section
    @server = Server.find(params[:id])

    @media = ServerMedia.new(@server)

    @section = @media.section(params[:section_id])

    # bad!
    @videos = Video.search(:conditions => ['server_id = ? AND section = ?', params[:id], params[:section_id]])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos
  # GET /videos.json
  def section_refresh
    @server = Server.find(params[:id])
    @media = ServerMedia.new(@server)
    @section = @media.section(params[:section_id])

    @videos = @media.refresh_media(params[:section_id])
  end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :host %><br />
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :port %><br />
    <%= f.number_field :port, :value => 32400 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/_videos.html.erb
<table>
  <tr>
    <th>Key</th>
    <th>Title</th>
    <th>Media type</th>
    <th>Section</th>
    <th>Server</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

Videos:  <%= @videos.size %>

<% @videos.each do |video| %>
  <tr>
    <td><%= video.key %></td>
    <td><%= video.title %></td>
    <td><%= video.media_type %></td>
    <td><%= video.section %></td>
    <td><%= link_to video.server.name, video.server %></td>
    <td><%= link_to 'Show', video %></td>
    <td><%= link_to 'Edit', edit_video_path(video) %></td>
    <td><%= link_to 'Destroy', video, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<h1>Listing servers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Host</th>
    <th>Address</th>
    <th>Port</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @servers.each do |server| %>
  <tr>
    <td><%= server.name %></td>
    <td><%= server.host %></td>
    <td><%= server.address %></td>
    <td><%= server.port %></td>
    <td><%= link_to 'Show', server %></td>
    <td><%= link_to 'Edit', edit_server_path(server) %></td>
    <td><%= link_to 'Destroy', server, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= link_to 'Refresh', "servers/#{server.id}/refresh" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/refresh.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Server:</b>
  <%= @server.name %>
</p>

Processed <%= @videos.count %> movies<br/>
<br/>
<%= link_to 'Videos', "/servers/#{@server.id}/videos" %><br/>
<br/>

<%= link_to 'Edit Server', edit_server_path(@server) %> |
<%= link_to 'Servers', servers_path %>

app/views/servers/section.html.erb
<h1><%= "#{@server.name} - #{@section[:title]}" %></h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  Videos:  <%= @videos.size %>

  <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
  <% end %>
</table>

app/views/servers/section_refresh.html.erb
<h1><%= "#{@server.name} - #{@section[:title]}" %></h1>

<p id="notice"><%= notice %></p>

Processed <%= @videos.count %> movies<br/>
<br/>
<%= link_to 'Show Section', "/servers/#{@server.id}/section/#{@section[:key]}" %><br/>
<br/>

<%= link_to 'Edit Server', edit_server_path(@server) %> |
<%= link_to 'Servers', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @server.name %>
</p>

<p>
  <b>Address:</b>
  <%= @server.host %>:<%= @server.port %>
</p>

<%= link_to 'Videos', "/servers/#{@server.id}/videos" %><br/>
<%= link_to 'Refresh media', "/servers/#{@server.id}/refresh" %><br/>

<br/>
<h3>Sections</h3>

<table>
  <tr>
    <th>Key</th>
    <th>Type</th>
    <th>Title</th>
    <th></th>
  </tr>

  <% @media.sections.each do |section| %>
      <tr>
        <td><%= section[:key] %></td>
        <td><%= section[:type] %></td>
        <td><%= section[:title] %></td>
        <td><%= link_to 'Show', "/servers/#{@server.id}/section/#{section[:key]}" %></td>
        <td><%= link_to 'Refresh', "/servers/#{@server.id}/section/#{section[:key]}/refresh" %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>

app/views/servers/videos.html.erb
<h1>Listing videos</h1>

<%= render 'videos' %>