config/routes.rb
Plexhack::Application.routes.draw do
  resources :video_notes

  resources :users

  resources :videos

  resources :servers

  resources :torrents

  match 'servers/:id/refresh' => 'servers#refresh'
  match 'servers/:id/videos' => 'servers#videos'
  match 'servers/:id/section/:section_id' => 'servers#section'
  match 'servers/:id/section/:section_id/refresh' => 'servers#section_refresh'

  root :to => 'servers#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :server
  attr_accessible :key, :media_type, :section, :title

  # this is bad and you should feel bad
  def self.search(conditions)
    find(:all, conditions)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :media_type %><br />
    <%= f.text_field :media_type %>
  </div>
  <div class="field">
    <%= f.label :section %><br />
    <%= f.number_field :section %>
  </div>
  <div class="field">
    <%= f.label :server %><br />
    <%= f.text_field :server %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <tr>
    <th>Key</th>
    <th>Title</th>
    <th>Media type</th>
    <th>Section</th>
    <th>Server</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td><%= video.key %></td>
    <td><%= video.title %></td>
    <td><%= video.media_type %></td>
    <td><%= video.section %></td>
    <td><%= link_to video.server.name, video.server %></td>
    <td><%= link_to 'Show', video %></td>
    <td><%= link_to 'Edit', edit_video_path(video) %></td>
    <td><%= link_to 'Destroy', video, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Key:</b>
  <%= @video.key %>
</p>

<p>
  <b>Title:</b>
  <%= @video.title %>
</p>

<p>
  <b>Media type:</b>
  <%= @video.media_type %>
</p>

<p>
  <b>Section:</b>
  <%= @video.section %>
</p>

<p>
  <b>Server:</b>
  <%= link_to @video.server.name, @video.server %>
</p>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>