config/routes.rb
Plexhack::Application.routes.draw do
  resources :video_notes

  resources :users

  resources :videos

  resources :servers

  resources :torrents

  match 'servers/:id/refresh' => 'servers#refresh'
  match 'servers/:id/videos' => 'servers#videos'
  match 'servers/:id/section/:section_id' => 'servers#section'
  match 'servers/:id/section/:section_id/refresh' => 'servers#section_refresh'

  root :to => 'servers#index'

end

app/models/video_note.rb
class VideoNote < ActiveRecord::Base
  belongs_to :video
  belongs_to :user
  attr_accessible :comment, :rating
end

app/controllers/video_notes_controller.rb
class VideoNotesController < ApplicationController
  # GET /video_notes
  # GET /video_notes.json
  def index
    @video_notes = VideoNote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @video_notes }
    end
  end

  # GET /video_notes/1
  # GET /video_notes/1.json
  def show
    @video_note = VideoNote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video_note }
    end
  end

  # GET /video_notes/new
  # GET /video_notes/new.json
  def new
    @video_note = VideoNote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video_note }
    end
  end

  # GET /video_notes/1/edit
  def edit
    @video_note = VideoNote.find(params[:id])
  end

  # POST /video_notes
  # POST /video_notes.json
  def create
    @video_note = VideoNote.new(params[:video_note])

    respond_to do |format|
      if @video_note.save
        format.html { redirect_to @video_note, notice: 'Video note was successfully created.' }
        format.json { render json: @video_note, status: :created, location: @video_note }
      else
        format.html { render action: "new" }
        format.json { render json: @video_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /video_notes/1
  # PUT /video_notes/1.json
  def update
    @video_note = VideoNote.find(params[:id])

    respond_to do |format|
      if @video_note.update_attributes(params[:video_note])
        format.html { redirect_to @video_note, notice: 'Video note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_notes/1
  # DELETE /video_notes/1.json
  def destroy
    @video_note = VideoNote.find(params[:id])
    @video_note.destroy

    respond_to do |format|
      format.html { redirect_to video_notes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/video_notes_helper.rb
module VideoNotesHelper
end

app/views/video_notes/_form.html.erb
<%= form_for(@video_note) do |f| %>
  <% if @video_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video_note.errors.count, "error") %> prohibited this video_note from being saved:</h2>

      <ul>
      <% @video_note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :video %><br />
    <%= f.text_field :video %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/video_notes/edit.html.erb
<h1>Editing video_note</h1>

<%= render 'form' %>

<%= link_to 'Show', @video_note %> |
<%= link_to 'Back', video_notes_path %>

app/views/video_notes/index.html.erb
<h1>Listing video_notes</h1>

<table>
  <tr>
    <th>Video</th>
    <th>User</th>
    <th>Rating</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @video_notes.each do |video_note| %>
  <tr>
    <td><%= video_note.video %></td>
    <td><%= video_note.user %></td>
    <td><%= video_note.rating %></td>
    <td><%= video_note.comment %></td>
    <td><%= link_to 'Show', video_note %></td>
    <td><%= link_to 'Edit', edit_video_note_path(video_note) %></td>
    <td><%= link_to 'Destroy', video_note, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video note', new_video_note_path %>

app/views/video_notes/new.html.erb
<h1>New video_note</h1>

<%= render 'form' %>

<%= link_to 'Back', video_notes_path %>

app/views/video_notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Video:</b>
  <%= @video_note.video %>
</p>

<p>
  <b>User:</b>
  <%= @video_note.user %>
</p>

<p>
  <b>Rating:</b>
  <%= @video_note.rating %>
</p>

<p>
  <b>Comment:</b>
  <%= @video_note.comment %>
</p>


<%= link_to 'Edit', edit_video_note_path(@video_note) %> |
<%= link_to 'Back', video_notes_path %>